ESTaPapelaria/Models/Artigo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESTaPapelaria.Models
{
    public class Artigo
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public double Preco { get; set; }
        public double Desconto { get; set; }
        public bool EmPromocao { get; set; }
    }
}

ESTaPapelaria/Controllers/ArtigosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ESTaPapelaria.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESTaPapelaria.Controllers
{
    public class ArtigosController : Controller
    {
        private List<Artigo> artigos = new List<Artigo>
        {
            new Artigo
            {
                Id= 2,
                Nome = "Esferográfica EST",
                Descricao = "Esferográfica de gel",
                Preco=1.99,
                Desconto = 0.10,
                EmPromocao = true
            },
            new Artigo
            {
                Id= 5,
                Nome = "Pen EST",
                Descricao = "Pen de 16GB",
                Preco=7.90,
                Desconto = 0.15,
                EmPromocao = false
            },
            new Artigo
            {
                Id= 6,
                Nome = "Clip EST",
                Descricao = "Clips coloridos",
                Preco=2.99,
                Desconto = 0.15,
                EmPromocao = true
            }
        };

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Listar()
        {
            return View(artigos);
        }

        public IActionResult Promocoes()
        {
            return View(artigos.Where(a => a.EmPromocao));
        }

        [HttpPost]
        public IActionResult Listar(string filtro)
        {
            var artigosFiltrados = from a in artigos select a;

            if (!String.IsNullOrEmpty(filtro))
            {
                artigosFiltrados = artigosFiltrados.Where(a => a.Nome.Contains(filtro));
            }

            return View(artigosFiltrados.ToList());
        }
    }
}

ESTaPapelaria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ESTaPapelaria.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ESTaPapelaria/Controllers/PapelariaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ESTaPapelaria.Controllers
{
    public class PapelariaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ESTaPapelaria/Views/Artigos/Listar.cshtml
@model IEnumerable<ESTaPapelaria.Models.Artigo>

@{
    ViewData["Title"] = "Artigos";
    Layout = "~/Views/Shared/_ESTLayout.cshtml";
}

<h2>Artigos</h2>

<form asp-controller="Artigos" asp-action="Listar" method="post">
    <p>
        Nome: <input type="text" name="filtro">
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desconto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmPromocao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desconto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmPromocao)
                </td>
            </tr>
        }
    </tbody>
</table>


@section Footer
    {
    <span>
        <b>
            Veja as nossas @Html.ActionLink("promoções","Promocoes","Artigos")!
        </b>
    </span>
}

ESTaPapelaria/Views/Artigos/Promocoes.cshtml
@model IEnumerable<ESTaPapelaria.Models.Artigo>

@{
    ViewData["Title"] = "Promoções";
    Layout = "~/Views/Shared/_ESTLayout.cshtml";
}

<h2>Promoções</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desconto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desconto)
                </td>
            </tr>
        }
    </tbody>
</table>

ESTaPapelaria/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <a href="/Papelaria/Index">
        <!-- Coloque a imagem aqui  -->
        <img src="~/images/papelaria.jpg" />
    </a>
</body>
</html>

ESTaPapelaria/Views/Papelaria/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ESTLayout.cshtml";
}

<h2>EST – a – Papelaria</h2>

@section Footer
{
    <span>Morada: EST Setúbal - Estefanilha - Telefone: 265 790 000</span>
}

ESTaPapelaria/Views/Shared/_ESTLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>_ESTLayout</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <style>
        .navbar-fixed-left {
            position: fixed; /* fixar o navegador */
            border-radius: 0;
            height: 100%; /* ocupar todo o tamanho na vertical*/
        }

        .container {
            padding-left: 220px; /*faz o render a 220px da esquerda*/
        }
    </style>

</head>
<body>
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-left" role="navigation">

        <div class="container-fluid">

            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <!-- num smartphone, esconde opções do menu-->
                    <span class="sr-only">Toggle navigation</span> <!--for screen readers-->
                    <span class="icon-bar"></span> <!--para criar o symbolo “≡” dentro do botão-->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand collapse navbar-collapse" href="#">EST-a-Papelaria</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul>
                    @*<li class="active"><a href="#" target="_blank">Home</a></li>
                        <li><a href="#" target="_blank">Listar produtos</a></li>
                        <li><a href="#" target="_blank">Contactos</a></li>*@
                    <li>  @Html.ActionLink("Home", "Index", "Papelaria")  </li>
                    <li>  @Html.ActionLink("Lista", "Listar", "Artigos") </li>
                    <li>  @Html.ActionLink("Promoções", "Promocoes", "Artigos") </li>
                </ul>
            </div>

        </div>

    </nav>

    <div class="container body-content container-fluid">

        @RenderBody()
        <hr />

        @* <footer>
            <!-- &copy é substituído pelo símbolo copyright-->
            <p>&copy; @DateTime.Now.Year – EST-a-Papelaria Online</p>
        </footer> *@

        <div class="row">
            <div class="col-xs-12">
                <div class="row">
                    <footer>
                        @RenderSection("Footer", required: false)
                    </footer>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>